os: linux

language: generic

services:
  - docker

before_install:
  - docker  build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e  "CI=true" react-test npm run test

after_success:
  - docker build -t tikzsz/client ./client
  - docker build -t tikzsz/nginx ./nginx
  - docker build -t tikzsz/server ./server 
  - docker build -t tikzsz/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push  tikzsz/client 
  - docker push  tikzsz/nginx 
  - docker push  tikzsz/server  
  - docker push  tikzsz/worker 
  
